FROM node:16-alpine

EXPOSE 5000

WORKDIR /usr/src/app

COPY package* ./

RUN npm install

RUN npm install -g serve

COPY . .

# This env was changed from http://localhost:8000 
ENV REACT_APP_BACKEND_URL=http://localhost/api

RUN npm run build

CMD ["serve", "-s", "-l", "5000", "build"]

