version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    container_name: example-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=examplepassword
    volumes:
      - ./database:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: redis-cache
    volumes:
      - ./cache:/data
 
  backend:
    image: example-backend
    container_name: example-backend
    build: ../../material-applications/example-backend/
    environment:
      - PORT=8000
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis-cache
      - POSTGRES_HOST=example-postgres  
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=examplepassword
    depends_on: 
      - db
    ports:
      - 8000:8000

  frontend:
    image: example-frontend
    container_name: example-frontend
    build: ../../material-applications/example-frontend
    ports:
      - 5000:5000

#  reverse-proxy:
#    image: nginx:1.21-alpine
#    container_name: example-nginx
#    volumes: 
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - 80:80
