version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-cache
  backend:
    image: example-backend
    container_name: example-backend
    build: ../../material-applications/example-backend/
    ports: 
      - 8000:8000
    environment:
      - PORT=8000
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis-cache
  frontend:
    image: example-frontend
    container_name: example-frontend
    build: ../../material-applications/example-frontend
    ports:
      - 5000:5000

